name: Quarto Publish

on:
  push:
    branches:
      - main # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Restore R packages with renv
        run: R -e "install.packages('renv'); renv::restore()"

      - name: Install fonts (Gentium)
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq wget unzip fontconfig
          wget -O gentium.zip "https://software.sil.org/downloads/r/gentium/GentiumPlus-6.200.zip"
          unzip gentium.zip -d gentium
          sudo mkdir -p /usr/share/fonts/truetype/gentium
          sudo cp gentium/GentiumPlus-6.200/*.ttf /usr/share/fonts/truetype/gentium/
          fc-cache -f -v

      - name: Install Quarto Extensions
        run: |
          quarto install --no-prompt extension shafayetShafee/code-fullscreen
          quarto install --no-prompt extension cl-roberts/code-appendix

      - name: Render Quarto site
        run: quarto render indexing-categorical-predictors.qmd --output-dir public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
