on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    container: inigourrestarazu/r-bayes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      #  - name: Set up Quarto
      #    uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Install fonts (Gentium)
        run: |
          apt-get update -qq && apt-get install -y -qq wget unzip fontconfig
          wget -O gentium.zip "https://software.sil.org/downloads/r/gentium/GentiumPlus-6.200.zip"
          unzip gentium.zip -d gentium
          mkdir -p /usr/share/fonts/truetype/gentium
          cp gentium/GentiumPlus-6.200/*.ttf /usr/share/fonts/truetype/gentium/
          fc-cache -f -v
          quarto install tinytex

      - name: Install Quarto Extensions
        run: |
          quarto install --no-prompt extension shafayetShafee/code-fullscreen
          quarto install --no-prompt extension cl-roberts/code-appendix

      - name: Render and Publish
        run: |
          quarto render indexing-categorical-predictors.qmd
          quarto publish gh-pages --no-publish --no-prompt
          mv indexing-categorical-predictors.html index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
